### PR TITLE
update the original PDF aadithya20a.pdf which was not compiled correctly. 

### PR DESCRIPTION
**Pull request by jianfenglu**

### CODE REVIEW

**Review by lawrennd — APPROVED** [review]

**Comment by lawrennd** [comment]
Hi Jianfeng, looks fine, although in passing I note that author first names are missing (I think normally they are there in full).

**Comment by jianfenglu** [comment]
Right. The authors seem to prefer that way.

**Comment by jianfenglu** [comment]
Update another PDF which was not compiled correctly. Please merge, thanks!

**Comment by lawrennd** [comment]
Thanks Jianfeng!

**Pull request merged**
